var num1 = 5;
var num2 = 10;
var sum = num1 + num2;
var num3 = 5;
var num4 = 5;
var sum2 = num3 * num4;
var Harry = 50;
var saifee = 100;
var total = Harry / saifee;
var num5 = 10;
var num6 = 10;
var sum3 = num5 - num6;
console.log("Sum: " + sum);
console.log("Sum2:" + sum2);
console.log(total);
console.log(sum3);
let variable = 0;
variable = 5;
const additionResult = +1;
console.log(additionResult);
const multiplyResult = 10 * 5;
console.log(multiplyResult);
const divisionResult = 0 / 12;
console.log(divisionResult);
const subtractionResult = 10 - 5;
console.log(subtractionResult);
export {};
